name: Deploy

on:
  # Manual trigger with environment selection
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: "Select the environment you want to deploy to."
        required: true
        default: develop
        choices:
          - develop
          - production

  # Automatic trigger on push to the develop branch
  push:
    branches:
      - develop # Automatically deploy on push to the develop branch

jobs:
  run_tests:
    uses: ./.github/workflows/common.yml
  
  build_and_deploy_develop:
    name: Build and Deploy to Develop
    runs-on: ubuntu-latest
    needs: [run_tests]
    if: ${{ inputs.ENVIRONMENT }} == 'develop' || github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Ensure this matches your project's Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the Vite app
        run: npm run build # This will generate the dist directory

      - name: List dist directory contents
        run: ls -al dist

      - name: Deploy to server using rsync
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr
          path: ./dist/
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
          remote_user: ${{ secrets.DEPLOY_USER }}

      - name: Restart Nginx on the server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USER }}
          script: |
            echo "${{ secrets.DEPLOY_PASSWORD }}" | sudo -S systemctl restart nginx
