name: Deploy React TypeScript App to DigitalOcean Droplet

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: "Select the environment you want to deploy to."
        required: true
        default: staging
        choices:
          - staging
          - production

jobs:
  run_tests:
    uses: ./.github/workflows/common.yml
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    needs: [run_tests]
    # TODO: we will change this to use github environment secrets
    # https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment
    # for now using this way, until we active our github teams account
    if: ${{ inputs.ENVIRONMENT }} == 'staging'
    steps:
      - uses: actions/checkout@v3
      - name: Copy code to server
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr
          path: ./dist/
          remote_path: ${{ secrets.DEPLOYMENT_DIRECTORY }}
          remote_host: ${{ secrets.SSH_HOST_NAME }}
          remote_port: ${{ secrets.SSH_PORT }}
          remote_key: ${{ secrets.SSH_SECRET }}
          remote_user: ${{ secrets.SSH_USERNAME  }}

      - name: Start up the docker container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST_NAME}}
          key: ${{ secrets.SSH_SECRET }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            mkdir -p ~/.ssh
            echo "$SSH_SECRET" | tr -d '\r' > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H $SSH_HOST_NAME >> ~/.ssh/known_hosts

            # Restart Nginx using sshpass to handle the password
            sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST_NAME "echo $SSH_PASSWORD | sudo -S systemctl restart nginx"
